// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stbdqwgtfcaietkbvxpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0YmRxd2d0ZmNhaWV0a2J2eHBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODM5ODYsImV4cCI6MjA2Njk1OTk4Nn0.NoLjvIuF_zWP00A9Hy5vzhS3NR0LjoDRIwmy6NShjoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});